### ISSUE TITLE
AttributeError: module 'grid' has no attribute 'svo_intersect'

### ISSUE THREAD

**Issue by qgh66** [JunyuanDeng/NeRF-LOAM#22]
`PatchWorkpp::PatchWorkpp() - INITIALIZATION COMPLETE
Decoder(
  (pe): Same()
  (pts_linears): ModuleList(
    (0): Linear(in_features=16, out_features=256, bias=True)
    (1): Linear(in_features=256, out_features=256, bias=True)
  )
  (sdf_out): Linear(in_features=256, out_features=1, bias=True)
)
******* initializing first_frame: 0
initializing the first frame ...
mapping process started!!!!!!!!!
frame id 1
trans  tensor([0., 0., 0.], device='cuda:0')
insert keyframe
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/NeRF-LOAM/src/mapping.py", line 107, in spin
    self.do_mapping(share_data, tracked_frame, selection_method='current')
  File "/home/NeRF-LOAM/src/mapping.py", line 179, in do_mapping
    bundle_adjust_frames(
  File "/home/NeRF-LOAM/src/variations/render_helpers.py", line 394, in bundle_adjust_frames
    final_outputs = render_rays(
  File "/home/NeRF-LOAM/src/variations/render_helpers.py", line 211, in render_rays
    intersections, hits = ray_intersect(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/NeRF-LOAM/src/variations/voxel_helpers.py", line 534, in ray_intersect
    pts_idx, min_depth, max_depth = svo_ray_intersect(
  File "/home/NeRF-LOAM/src/variations/voxel_helpers.py", line 110, in forward
    inds, min_depth, max_depth = _ext.svo_intersect(
AttributeError: module 'grid' has no attribute 'svo_intersect'`
Hi, I have encountered this problem when running python demo/run.py configs/kitti/kitti_00.yaml. And I have seen the same problem in github while that solution didn't work for me. Is there another possible reason for this?

**Comment by JunyuanDeng** [comment]
Sorry for late reply, we are in vacation these days.

Could you please check that the third party is installed successfully? There are three of them, make sure all of them are installed.
